# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UnitTestDemoTests' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UnitTestDemoTests
pod 'AFNetworking'
pod 'STAlertView'

  target 'UnitTestDemoTestsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnitTestDemoTestsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
